Mansards/Mansards/Controllers/BuildingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mansards.Controllers
{
    public class BuildingsController : Controller
    {
        // GET: Buildings
        public ActionResult Mavra29()
        {
            ViewBag.Title = "Я.Мавра 29";
            return View("Mavra29");
        }

        public ActionResult Mavra33()
        {
            ViewBag.Title = "Я.Мавра 33";
            return View("Mavra33");
        }

        public ActionResult Mavra31()
        {
            ViewBag.Title = "Я.Мавра 31";
            return View("Mavra31");
        }
    }
}

Mansards/Mansards/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Мансарды Столицы</title>
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("~/Content/Index.css")
    @Styles.Render("~/Content/NavigationBar.css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/Mavra33.js")

</head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top">
            <img src="~/Images/Logo.png"/>
            @Html.ActionLink("Мансарды Столицы", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @name = "header-link" })
            <div class="container-fluid">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("ул.Я.Мавра, 33", "Mavra33", "Buildings")</li>
                        <li>@Html.ActionLink("ул.Я.Мавра, 29", "Mavra29", "Buildings")</li>
                        <li>@Html.ActionLink("ул.Я.Мавра, 31", "Mavra31", "Buildings")</li>
                        <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>  
        </div>

    <div class="container-fluid">
        @RenderBody()
        <hr />
    </div>
</body>
    
   
</html>